In [1]:
pip install fredapi

Requirement already satisfied: fredapi in c:\users\hi\anaconda3\lib\site-packages (0.4.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\hi\anaconda3\lib\site-packages (from fredapi) (1.0.5)
Requirement already satisfied: numpy>=1.13.3 in c:\users\hi\anaconda3\lib\site-packages (from pandas->fredapi) (1.18.5)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\hi\anaconda3\lib\site-packages (from pandas->fredapi) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\hi\anaconda3\lib\site-packages (from pandas->fredapi) (2020.1)
Requirement already satisfied: six>=1.5 in c:\users\hi\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas->fredapi) (1.15.0)

In [2]:
import pandas as pd
from fredapi import Fred
fred = Fred(api_key='ba62defdd2d357a1a45f8e2f0d70816a')

In [3]:
bitcoinprice = fred.get_series('CBBTCUSD')
goldprice = fred.get_series('ID7108')
market = fred.get_series('SP500')
riskfreerate = fred.get_series('TB3MS')

In [4]:
df = pd.concat([bitcoinprice,goldprice,market,riskfreerate], axis=1)

In [5]:
df.columns = ('bitcoinprice','goldprice','market','riskfreerate')

In [6]:
df = df.loc['2017-01-01':'2020-12-31']

In [7]:
df = df.fillna(method='ffill')

In [8]:
#Will generate data with respect to monthly basis
df = df[df.index.day==1]
df

            bitcoinprice  goldprice   market  riskfreerate
2017-01-01        992.95      421.9      NaN          0.51
2017-02-01        992.75      437.2  2279.55          0.52
2017-03-01       1230.00      449.6  2395.96          0.74
2017-04-01       1092.00      453.3  2362.72          0.80
2017-05-01       1436.50      450.4  2388.33          0.89
2017-06-01       2419.99      463.0  2430.06          0.98
2017-07-01       2423.63      441.9  2423.41          1.07
2017-08-01       2732.59      457.9  2476.35          1.01
2017-09-01       4947.99      484.7  2476.55          1.03
2017-10-01       4394.81      459.6  2519.36          1.07
2017-11-01       6783.69      460.4  2579.36          1.23
2017-12-01      10869.84      456.4  2642.22          1.32
2018-01-01      13480.01      475.9  2673.61          1.41
2018-02-01       9014.23      478.7  2821.98          1.57
2018-03-01      10895.92      479.1  2677.67          1.70
2018-04-01       6816.01      482.0  2640.87          1.76
2018-05-01       9072.29      473.7  2654.80          1.86
2018-06-01       7514.32      469.0  2734.62          1.90
2018-07-01       6349.50      453.1  2718.37          1.96
2018-08-01       7603.99      440.8  2813.36          2.03
2018-09-01       7191.08      433.5  2901.52          2.13
2018-10-01       6572.83      434.5  2924.59          2.25
2018-11-01       6344.00      444.0  2740.37          2.33
2018-12-01       4142.01      448.7  2760.17          2.37
2019-01-01       3826.10      464.4  2506.85          2.37
2019-02-01       3437.50      475.9  2706.53          2.39
2019-03-01       3806.17      467.3  2803.69          2.40
2019-04-01       4137.00      467.4  2867.19          2.38
2019-05-01       5321.15      463.7  2923.73          2.35
2019-06-01       8558.01      481.8  2752.06          2.17
2019-07-01      10570.62      506.1  2964.33          2.10
2019-08-01      10417.24      537.7  2953.56          1.95
2019-09-01       9769.64      554.7  2926.46          1.89
2019-10-01       8323.43      541.5  2940.25          1.65
2019-11-01       9268.00      539.2  3066.91          1.54
2019-12-01       7413.84      533.9  3140.98          1.54
2020-01-01       7174.32      555.0  3230.78          1.52
2020-02-01       9375.06      568.1  3225.52          1.52
2020-03-01       8490.30      595.4  2954.22          0.29
2020-04-01       6719.39      583.4  2470.50          0.14
2020-05-01       8813.90      617.3  2830.71          0.13
2020-06-01      10212.38      620.8  3055.73          0.16
2020-07-01       9239.09      642.6  3115.86          0.13
2020-08-01      11805.82      730.8  3271.12          0.10
2020-09-01      11911.74      707.7  3526.65          0.11
2020-10-01      10598.64      690.2  3380.80          0.10
2020-11-01      13784.52      694.6  3269.96          0.09
2020-12-01      18763.35      658.5  3662.45          0.09